---
# linter.yaml
# Sources: 
# - https://github.com/zanix/home-assistant-blueprints/
# - https://github.com/frenck/action-home-assistant
# - https://github.com/creyD/prettier_action

name: linters
# yamllint disable-line rule:truthy
on: [push, workflow_dispatch]

jobs:
  yaml_lint:
    name: ğŸ§¹ yamllint
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v4
      - name: ğŸš€ Run yamllint
        uses: frenck/action-yamllint@v1.5

  # remark_lint:
  #   name: ğŸ§¹ Remark Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: ğŸ“¥ Check out repository
  #       uses: actions/checkout@v4
  #     - name: ğŸš€ Run Remark lint
  #       uses: "docker://pipelinecomponents/remark-lint:latest"
  #       continue-on-error: true
  #       with:
  #         args: "remark --no-stdout --color --frail --use preset-lint-recommended ."
  
  # prettier:
  #   name: Prettier
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: â¤µï¸ Check out code from GitHub
  #       uses: actions/checkout@v4

  #     - name: ğŸš€ Prettify code
  #       uses: creyD/prettier_action@v4.6
  #       with:
  #         rettier_options: --write **/*.{json,js,md,yaml}
  #       # env:
  #       #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}